// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "augsynth_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// balancing_grad_multisynth
arma::mat balancing_grad_multisynth(arma::mat theta, List opts);
RcppExport SEXP _augsynth_balancing_grad_multisynth(SEXP thetaSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(balancing_grad_multisynth(theta, opts));
    return rcpp_result_gen;
END_RCPP
}
// make_balancing_grad_multisynth
gptr make_balancing_grad_multisynth();
RcppExport SEXP _augsynth_make_balancing_grad_multisynth() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(make_balancing_grad_multisynth());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_augsynth_balancing_grad_multisynth", (DL_FUNC) &_augsynth_balancing_grad_multisynth, 2},
    {"_augsynth_make_balancing_grad_multisynth", (DL_FUNC) &_augsynth_make_balancing_grad_multisynth, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_augsynth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
