# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic balancing loss gradient
balancing_grad_multisynth <- function(theta, opts) {
    .Call('_augsynth_balancing_grad_multisynth', PACKAGE = 'augsynth', theta, opts)
}

make_balancing_grad_multisynth <- function() {
    .Call('_augsynth_make_balancing_grad_multisynth', PACKAGE = 'augsynth')
}

