# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gradient for Multiple synthetic controls and absolute time
grad_multisynth_absolute <- function(theta, opts) {
    .Call('_augsynth_grad_multisynth_absolute', PACKAGE = 'augsynth', theta, opts)
}

make_grad_multisynth_absolute <- function() {
    .Call('_augsynth_make_grad_multisynth_absolute', PACKAGE = 'augsynth')
}

#' Gradient for Multiple synthetic controls and relative time
grad_multisynth_relative <- function(theta, opts) {
    .Call('_augsynth_grad_multisynth_relative', PACKAGE = 'augsynth', theta, opts)
}

make_grad_multisynth_relative <- function() {
    .Call('_augsynth_make_grad_multisynth_relative', PACKAGE = 'augsynth')
}

